name: "todos-action"
description: "A composite action to create GitHub issues from TODO comments"
inputs:
  APP_ID:
    description: "GitHub App ID"
    required: true
  APP_PRIVATE_KEY:
    description: "GitHub App Private Key"
    required: true
  PROJECT:
    description: "GitHub Project to add issues to"
    required: false
runs:
  using: "composite"
  steps:
    - name: Generate GitHub App Token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      id: app-token
      with:
        app-id: ${{ inputs.APP_ID }}
        private-key: ${{ inputs.APP_PRIVATE_KEY }}
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: alstr/todo-to-issue-action@64aca8fda7023259aada83ba44ad988c4c443657 # v5.1.14
      with:
        AUTO_ASSIGN: true
        CLOSE_ISSUES: true
        PROJECT: ${{ inputs.PROJECT }}
        PROJECTS_SECRET: ${{ steps.app-token.outputs.token }}
