name: "todos-action"
description: "A composite action to create GitHub issues from TODO comments"
inputs:
  APP_ID:
    description: "GitHub App ID"
    required: true
  APP_PRIVATE_KEY:
    description: "GitHub App Private Key"
    required: true
  PROJECT:
    description: "GitHub Project to add issues to"
    required: false
runs:
  using: "composite"
  steps:
    - name: Generate GitHub App Token
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      id: app-token
      with:
        app-id: ${{ inputs.APP_ID }}
        private-key: ${{ inputs.APP_PRIVATE_KEY }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: alstr/todo-to-issue-action@c45b007d85c8edf3365b139a9d4c65793e7c674f # v5.1.13
      with:
        AUTO_ASSIGN: true
        CLOSE_ISSUES: true
        PROJECT: ${{ inputs.PROJECT }}
        PROJECTS_SECRET: ${{ steps.app-token.outputs.token }}
