name: install-flux-action
description: Installs Flux in a Kubernetes cluster using the Flux CLI.
runs:
  using: "composite"
  steps:
    - name: ⚙️ Install Flux
      shell: bash
      run: |
        flux check --pre
        flux install
