name: flux-gitops-deploy-action
description: "Push manifests to OCI and deploy using Flux"
inputs:
  DEPLOYMENT_ENV:
    description: "Deployment environment"
    required: true
  KUBE_CONFIG:
    description: "Kubeconfig for the target cluster"
    required: true
  GITHUB_TOKEN:
    description: "The token to use for accessing GHCR"
    required: true
runs:
  using: "composite"
  steps:
    - name: 🔨 Create kubeconfig
      id: get-context
      shell: bash
      run: |
        mkdir -p ~/.kube
        echo "${KUBE_CONFIG}" > ~/.kube/config
        chmod 600 ~/.kube/config
        export KUBECONFIG=~/.kube/config
        export KUBE_CONFIG_PATH=~/.kube/config
        context=$(kubectl config current-context)
        echo "context=$context" >> $GITHUB_OUTPUT
      env:
        KUBE_CONFIG: ${{ inputs.KUBE_CONFIG }}

    - name: 🗳️ Push to GHCR OCI
      shell: bash
      run: |
        flux push artifact oci://ghcr.io/${GITHUB_REPOSITORY}/manifests-${DEPLOYMENT_ENV}:${GITHUB_SHA} \
          --path=./k8s \
          --source="$(git config --get remote.origin.url)" \
          --revision="$(git branch --show-current)@sha1:$(git rev-parse HEAD)" \
          --creds=${GITHUB_ACTOR}:${GITHUB_TOKEN}
        sanitized_tag=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
        flux tag artifact oci://ghcr.io/${GITHUB_REPOSITORY}/manifests-${DEPLOYMENT_ENV}:${GITHUB_SHA} \
          --tag "$sanitized_tag" \
          --creds=${GITHUB_ACTOR}:${GITHUB_TOKEN}
        flux tag artifact oci://ghcr.io/${GITHUB_REPOSITORY}/manifests-${DEPLOYMENT_ENV}:${GITHUB_SHA} \
          --tag latest \
          --creds=${GITHUB_ACTOR}:${GITHUB_TOKEN}
      env:
        DEPLOYMENT_ENV: ${{ inputs.DEPLOYMENT_ENV }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: 🔁 Reconcile
      shell: bash
      run: |
        ksail update \
          --context ${CONTEXT} \
          --deployment-tool Flux \
          --validate false \
          --publish false \
          --timeout 10m
      env:
        CONTEXT: ${{ steps.get-context.outputs.context }}
