name: Dockerfile Lint Action
description: Lint Dockerfiles using Hadolint

inputs: {}

runs:
  using: "composite"
  steps:
    - name: Run Hadolint
      uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
      with:
        recursive: true
