name: cleanup-ghcr-action
description: Clean up old GitHub Container Registry (GHCR) packages
inputs:
  older-than:
    description: "Delete images older than this duration (e.g., 1 year)"
    required: false
    default: "1 year"
  keep-n-tagged:
    description: "Number of tagged images to keep"
    required: false
    default: "10"
runs:
  using: "composite"
  steps:
    - uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
      with:
        older-than: ${{ inputs.older-than }}
        keep-n-tagged: ${{ inputs.keep-n-tagged }}
