name: setup-ksail-action
description: |
  Installs KSail CLI via Homebrew

runs:
  using: "composite"
  steps:
    - name: 📦 Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@5d6d1da704bb2434e19e77cd91a876f2b333a06b # main

    - name: ⤵️ Install KSail
      shell: bash
      run: |
        brew tap devantler-tech/formulas
        brew install ksail
