name: setup-ksail-action
description: |
  Installs KSail CLI via Homebrew

runs:
  using: "composite"
  steps:
    - name: 📦 Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@e2455dd8b43b9e9dc8c20e368bafa1d80584480c # main

    - name: ⤵️ Install KSail
      shell: bash
      run: |
        brew tap devantler-tech/formulas
        brew install ksail
