name: setup-ksail-action
description: |
  Installs KSail CLI via Homebrew

runs:
  using: "composite"
  steps:
    - name: 📦 Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@1c974ca2b216a546539402bb876925d13a71eff5 # main

    - name: ⤵️ Install KSail
      shell: bash
      run: |
        brew tap devantler-tech/formulas
        brew install ksail
