name: setup-ksail-action
description: |
  Installs KSail CLI via Homebrew

runs:
  using: "composite"
  steps:
    - name: 📦 Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@ac399ee818eb2bb93b838aeccd2cbaa6272e2403 # main

    - name: ⤵️ Install KSail
      shell: bash
      run: |
        brew tap devantler-tech/formulas
        brew install ksail
