name: sync-labels-action
description: Sync GitHub labels
inputs:
  config-file:
    description: "URL or path to the labels config file"
    required: false
    default: "https://raw.githubusercontent.com/devantler-tech/github-actions/refs/heads/main/.github/labels.yaml"
  delete-other-labels:
    description: "Whether to delete labels not in the config"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
      with:
        config-file: ${{ inputs.config-file }}
        delete-other-labels: ${{ inputs.delete-other-labels }}
