name: 🎉 Release

on:
  push:
    branches:
      - main

permissions: {}


jobs:
  release:
    uses: devantler-tech/reusable-workflows/.github/workflows/reusable-workflow-release.yaml@
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
