name: Auto-merge
on:
  workflow_call:
  pull_request:
  merge_group:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: startsWith(github.event_name, 'pull_request') && (github.actor == 'dependabot[bot]' || github.actor == 'botantler-tech[bot]' || github.actor == 'devantler')
    steps:
      - name: Generate GitHub App Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: 📑 Checkout
        uses: actions/checkout@v4
      - name: ✅ Approve pull request
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: 🤖 Enable auto-merge
        run: gh pr merge --auto --squash ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
