name: Auto-merge
on:
  workflow_call:
  pull_request:
  merge_group:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: startsWith(github.event_name, 'pull_request') && (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'botantler-tech[bot]' || github.event.pull_request.user.login == 'devantler')
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: 🧪 Run auto-merge-action
        uses: devantler-tech/github-actions/composite-actions/auto-merge-action@a8f34bd9d1876705e326007885beaa5f8c5901d0 # v1.5.1
        with:
          app_id: ${{ vars.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
