name: Publish .NET Application to GitHub Releases and Homebrew Taps
on:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: 📑 Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
