name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
  pull_request:
  merge_group:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Test .NET solution or project
        uses: ./composite-actions/dotnet-test-action
        with:
          app_id: ${{ vars.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
