name: GitOps Validate

on:
  workflow_call:
  pull_request:
  merge_group:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@v4
      - name: 📦 Setup Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: ⤵️ Install KSail
        run: |
          brew tap devantler-tech/formulas
          brew install ksail
      - name: 🧹 Validate GitOps cluster configuration
        run: |
          ksail validate
