name: Auto-merge (Required Workflow)
on:
  pull_request:
  merge_group:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    uses: devantler-tech/github-actions/reusable-workflows/auto-merge.yaml@main
    secrets: inherit
