name: CD - GitOps Deploy (Flux)

on:
  workflow_call:
    secrets:
      KUBE_CONFIG:
        required: true
        description: "Kubernetes config file"
      SOPS_AGE_KEY:
        required: true
        description: "Age key for SOPS"
    inputs:
      DEPLOYMENT_ENV:
        type: string
        required: true
        default: dev
        description: "Deployment environment (dev, prod)"

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.DEPLOYMENT_ENV }}
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: ⚙️ Setup flux
        uses: fluxcd/flux2/action@6bf37f6a560fd84982d67f853162e4b3c2235edb # v2.6.4

      - name: ⚙️ Setup KSail
        uses: devantler-tech/github-actions/composite-actions/setup-ksail-action@e2bd11618534558a19a1903468a9f1ba5daf90db # v1.8.3

      - name: 🚀 Deploy
        uses: devantler-tech/github-actions/composite-actions/flux-gitops-deploy-action@e2bd11618534558a19a1903468a9f1ba5daf90db # v1.8.3
        with:
          DEPLOYMENT_ENV: ${{ inputs.DEPLOYMENT_ENV }}
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

