name: GitOps Test

on:
  workflow_call:
    secrets:
      KSAIL_SOPS_KEY:
        required: false
    inputs:
      HOSTS_FILE:
        required: false
        type: string
      ROOT_CA_CERT_FILE:
        required: false
        type: string
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: 📦 Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: ⤵️ Install KSail
        run: |
          brew tap devantler-tech/formulas
          brew install ksail
      - name: 🌐 Add hosts
        run: |
          if [ -f "${{ inputs.HOSTS_FILE || vars.HOSTS_FILE }}" ]; then
            sudo tee -a /etc/hosts < "${{ inputs.HOSTS_FILE || vars.HOSTS_FILE }}"
          fi
      - name: 🔐 Install root CA
        run: |
          if [ -f "${{ inputs.ROOT_CA_CERT_FILE || vars.ROOT_CA_CERT_FILE }}" ]; then
            sudo cp "${{ inputs.ROOT_CA_CERT_FILE || vars.ROOT_CA_CERT_FILE }}" /usr/local/share/ca-certificates/root-ca.crt
            sudo update-ca-certificates
          fi
      - name: 🔑 Import Age key
        env:
          KSAIL_SOPS_KEY: ${{ secrets.KSAIL_SOPS_KEY }}
        if: ${{ env.KSAIL_SOPS_KEY != '' }}
        run: ksail secrets import "${{ secrets.KSAIL_SOPS_KEY }}"
      - name: 🛥️🐳 Provision cluster
        run: |
          ksail up
      - name: 🔥 Teardown cluster
        if: always()
        run: ksail down
