name: Sync labels

on:
  workflow_call:

permissions:
  issues: write

jobs:
  sync:
    name: Run EndBug/label-sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: "https://raw.githubusercontent.com/devantler-tech/github-actions/refs/heads/main/.github/labels.yaml"
          delete-other-labels: true
