name: CI - GitOps Validate

on:
  workflow_call:
  pull_request:
  merge_group:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: ⚙️ Setup KSail
        uses: ./composite-actions/setup-ksail-action

      - name: 🧹 Validate GitOps cluster configuration
        run: |
          ksail validate
