name: CD - GitOps Deploy (Flux)

on:
  workflow_call:
    secrets:
      KUBE_CONFIG:
        required: true
        description: "Kubernetes config file"
      SOPS_AGE_KEY:
        required: true
        description: "Age key for SOPS"
    inputs:
      DEPLOYMENT_ENV:
        type: string
        required: true
        default: dev
        description: "Deployment environment (dev, prod)"

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.DEPLOYMENT_ENV }}
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: ⚙️ Setup flux
        uses: fluxcd/flux2/action@709b17ce59d184427c1395bc70f496ba528d3bee # v2.6.4

      - name: ⚙️ Setup KSail
        uses: ./composite-actions/setup-ksail-action

      - name: 🚀 Deploy
        uses: ./composite-actions/flux-gitops-deploy-action
        with:
          DEPLOYMENT_ENV: ${{ inputs.DEPLOYMENT_ENV }}
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

