name: Sync labels
on:
  workflow_call:

permissions:
  issues: write

jobs:
  sync:
    name: Run EndBug/label-sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label-sync@v2
        with:
          config-file: "https://raw.githubusercontent.com/devantler-tech/.github/refs/heads/main/.github/labels.yaml"
          delete-other-labels: true
