name: "TODOs"
permissions:
  issues: write
on:
  workflow_call:
    secrets:
      APP_PRIVATE_KEY:
        required: true

jobs:
  create-issues-from-todos:
    runs-on: "ubuntu-latest"
    steps:
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: alstr/todo-to-issue-action@v5
        with:
          AUTO_ASSIGN: true
          CLOSE_ISSUES: true
